repos:
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
      - id: mypy
        language: system
        exclude: tests/
