name: Test Patches

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # check-version-branch:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     is_version_branch: ${{ steps.check_version_branch.outputs.is_version_branch }}
  #   steps:
  #     - name: Checkout PR branch
  #       uses: actions/checkout@v2

  #     - name: Get target branch
  #       id: get_target_branch
  #       run: echo "::set-output name=target_branch::$(jq -r .pull_request.base.ref $GITHUB_EVENT_PATH)"

  #     - name: Check if target branch is a version branch
  #       id: check_version_branch
  #       run: |
  #         if [[ "${{ steps.get_target_branch.outputs.target_branch }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  #           echo "::set-output name=is_version_branch::true"
  #         else
  #           echo "::set-output name=is_version_branch::false"
  #         fi

  apply-patches:
    # needs: check-version-branch
    # if: needs.check-version-branch.outputs.is_version_branch == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: workflows-test
          # ref: add ref to checkout to target branch
      
      - name: Checkout patches
        id: checkout-patches
        uses: actions/checkout@v4
        with:
          repository: Marcin-s-Org/workflows-patches
          token: ${{ steps.generate-token.outputs.token }}  # token is not available in this step? needs to be stored?
          path: workflows-patches
          # ref: add reg to checkout to target branch

      - run: ls
      - name: Apply patches
        id: apply_patches
        run: |
          cd workflows-test
          git apply ../workflows-patches/patches/**.patch

