name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 1' # At 08:00 on Monday.

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - run: python -m pip install poetry pre-commit
      - run: poetry lock
      - run: poetry export --without-hashes --dev -f requirements.txt -o requirements_dev.txt -E python
      - run: poetry export -f requirements.txt --without-hashes -o requirements.txt
      - run: pre-commit autoupdate
      - run: git status

      - env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_WORKFLOW_KEY }}
        run: |
          git checkout -b bump-dependencies
          git add *
          git commit -m "Bump dependencies"
          git push origin bump-dependencies
          gh pr create -t "Bump dependencies" -b "Weekly update of backend dependencies." -l ":robot: bot" -l "test deployment"
